### ISSUE TITLE
O projeto é visado apenas para a àrea de Computação da UFCG?

### ISSUE THREAD

**Issue by viniciussousaazevedo** [ufcg-lsd/tuvens#1]
Olá! Pretendo ser aprendiz do "Andromedev" e achei muito interessante toda a proposta, estou dando meus primeiros passos em desenvolvimento web e adoraria participar ativamente do projeto! Ao ler a descrição, me surgiu uma dúvida quanto à área de atuação: O projeto é voltado apenas para os locais da universidade ligados à computação (LCC's, por exemplo) ou é algo mais geral, visando toda a universidade?

**Comment by thiagomanel** [comment]
oi @viniciussousaazevedo obrigado pelo interesse. o escopo do projeto é para ser algo mais geral, inclusive não limitado à UFCG.  Ou seja, nada no código vai ser específico para o nosso caso de computação.

Agora, o uso planejado, imediato, é para os ambientes de computação mesmo.

**Comment by thiagomanel** [comment]
fechando a issue, uma vez que @viniciussousaazevedo mandou um 👍
